-- MySQL Script generated by MySQL Workbench
-- Wed May  2 19:52:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogoc` DEFAULT CHARACTER SET utf8 ;
USE `blogoc` ;

-- -----------------------------------------------------
-- Table `blogoc`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogoc`.`posts` ;

CREATE TABLE IF NOT EXISTS `blogoc`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `status` ENUM('pending', 'published') NULL,
  `author_id` INT NULL,
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL DEFAULT NULL,
  `published_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogoc`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogoc`.`comments` ;

CREATE TABLE IF NOT EXISTS `blogoc`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `status` ENUM('pending', 'published') NULL,
  `post_id` INT NULL,
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blogoc`.`users` ;

CREATE TABLE IF NOT EXISTS `blogoc`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `create_at` DATETIME NULL,
  `update_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
